---
- name: Install Apache2
  hosts: 10.10.5.82
  become: true  # This allows the playbook to run with sudo privileges

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install Apache2
      apt:
        name: apache2
        state: present
      become: true
