---
- name: Install MySQL Server and Client
  hosts: 10.10.5.82   # Replace with the hostname or IP address of your target server
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
      when: ansible_os_family == "Debian"

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Install MySQL Client
      apt:
        name: mysql-client
        state: present
      when: ansible_os_family == "Debian"

    - name: Check if MySQL Server is running
      wait_for:
        host: 127.0.0.1
        port: 3306
        timeout: 60
      ignore_errors: yes
      register: mysql_running
      until: mysql_running is success

    - name: Set MySQL root password
      debconf:
        name: mysql-server
        question: "mysql-server/root_password"
        value: "12345"   # Replace with your desired root password
        vtype: password
      when: ansible_os_family == "Debian"

    - name: Set MySQL root password (again for confirmation)
      debconf:
        name: mysql-server
        question: "mysql-server/root_password_again"
        value: "12345"   # Replace with your desired root password
        vtype: password
      when: ansible_os_family == "Debian"
